# Tipo de simulação: STATIONARY ou TRANSIENT
simulation.type=TRANSIENT

# -----------------------------
# Parâmetros Gerais
# -----------------------------
queueCapacity=40
dronesPerWarehouse=20
meanServiceTime=0.5
pickupTime=2.0
flightTime=75.0
transferTime=2.5
phaseDuration=500.0
backlogThreshold=10
migrateBatch=3

# Semente base para reprodutibilidade
baseSeed=42

# -----------------------------
# Parâmetros Simulação Transiente (MainDronesSimulationMultRun)
# -----------------------------
transient.simTime=6000.0
transient.sampleStep=150.0
transient.warmupTime=0.0
transient.meanInterarrival=2.77
transient.runs=1
transient.smaWindow=3

# -----------------------------
# Parâmetros Simulação Estacionária (StationaryRun)
# -----------------------------
stationary.simTime=50000.0
stationary.warmupTime=10000.0
stationary.sampleStep=500.0
stationary.minAr=0.08
stationary.maxAr=0.3831578947368421
stationary.arStep=0.03789473684210526
stationary.replicas=500
