drones=100,200,300
ar.min=0.001
ar.max=5.0
xPointQuantity=20
maxQueueSize=100
totalPackages=1000
<<<<<<< HEAD
simulationNumber=1
=======
simulationNumber=3
>>>>>>> 209da03ff7b9fae6456a9ff716b18b2fa1f3ecec
